server:
  port: 8080

spring:
  application:
    name: application-service
  datasource:
    username: 'henri'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/products
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
