server:
  port: 8080

spring:
  application:
    name: application-service
  datasource:
    username: 'henri'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/applicationDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
