server:
  port: 8080

spring:
  application:
    name: application-service
  datasource:
    url: jdbc:postgresql://localhost:5432/application_db
    username: henri
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefereIpAddress: true
