services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: henri
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application_db
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: storage_db
    ports:
      - 27017:27017
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  mongodb:
    driver: bridge