server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefereIpAddress: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: APPLICATION-SERVICE
          uri: lb://application-service
          predicates:
            - Path=/v1/api/products/**
          filters:
            - RewritePath=/v1/api/products/(?<path>.*), /$\{path}
        - id: CALCULATOR-SERVICE
          uri: lb://calculator-service
          predicates:
            - Path=/calculator/**
          filters:
            - RewritePath=/calculator/(?<path>.*), /$\{path}
        - id: STORAGE-SERVICE
          uri: lb://storage-service
          predicates:
            - Path=/v1/api/delivery-infos/**
          filters:
            - RewritePath=/v1/api/delivery-infos/(?<path>.*), /$\{path}