server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefereIpAddress: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: APPLICATION-SERVICE
          uri: lb://application-service
          predicates:
            - Path=/rest/products/**
        - id: CALCULATOR-SERVICE
          uri: lb://calculator-service
          predicates:
            - Path=/rest/calculator/**