server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: https://localhost:8761/eureka/
    instance:
      prefereIpAddress: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/products/**
        - id: calculator-service
          uri: lb://calculator-service
          predicates:
            - Path=/calculator/**
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/importProducts/**

