services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: storage_db
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongodb: