server:
  port: 8082

spring:
  application:
    name: calculator-service

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefereIpAddress: true