server:
  port: 8083

spring:
  application:
    name: storage-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/storage_db

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefereIpAddress: true